---
kind: pipeline
name: default
type: docker

steps:
  - name: integration-test
    image: "attxproject/dockerize-drone-test:dev"
    commands:
      - "dockerize -wait tcp://mariadb:3306 -timeout 240s"

  - name: test & build
    image: golang:1.14
    commands:
      - cp .env.ci .env
      - go test -v -cover -coverpkg=./... ./pkg/...
      - cp .env.ci .env
      - go test -v -cover -coverpkg=./... ./godog_test.go
      - CGO_ENABLED=0 go build -o ./bin/app ./cmd/app.go
    when:
      branch:
        - master
    volumes:
      - name: go-cache
        path: /tmp

  - name: "image build"
    image: plugins/docker
    debug: true
    settings:
      repo: registry.hub.docker.com/medzoner/medzoner-go
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile
      registry: registry.hub.docker.com
      tags:
        - latest
        - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA}
    when:
      branch:
        - master

  - name: "tag config repo"
    image: medzoner/tools
    environment:
      SSH_KEY:
        from_secret: ssh_key
      TAG_REPO:
        from_secret: tag_repo
    volumes:
      - name: key
        path: /root/.ssh
    commands:
      - echo $SSH_KEY | base64 -d > /root/.ssh/id_rsa
      - echo $SSH_KEY | base64 -d > /root/private_key
      - chmod 600 /root/.ssh/id_rsa
      - eval `ssh-agent -s` && ssh-add
      - cd /tmp && git clone $TAG_REPO && cd medzoner-gitops
      - cp .env.prod .env
      - ./bin/app tag ${DRONE_BRANCH} medzoner ${DRONE_COMMIT_SHA} medzoner
    when:
      branch:
        - master

services:
    - name: mariadb
      image: mysql
      environment:
         MYSQL_DATABASE: ci_medzoner_go
         MYSQL_ROOT_PASSWORD: changeme

volumes:
    - name: go-cache
      host:
        path: /var/cache