version: "2.0"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - funlen
    - gci
    - gocognit
    - gocritic
    - gofmt
    - gofumpt
    - gosec
    - maintidx
    - makezero
    - musttag
    - nestif
    - nilerr
    - noctx
    - nosprintfhostport
    - prealloc
    - spancheck
    - tagalign
    - wrapcheck
    - zerologlint

run:
  issues-exit-code: 1

issues:
  exclude-dirs:
    - .cache
    - var
  exclude-rules:
    - path: _test\.go
      linters:
        - cyclop
        - gosec
        - dupl
        - funlen
        - errchkjson
        - depguard
        - govet
        - prealloc
        - gocritic
