language: go

go:
  - '1.14'

env:
  global:
    - DATABASE_DSN=root:changeme@tcp(127.0.0.1:3306)
    - DATABASE_NAME=ci_medzoner_go
    - DATABASE_DRIVER=mysql
    - ENV=test
    - MAILER_USER=medzoner@xxxx.fake
    - MAILER_PASSWORD=xxxxxxxxxxxxxx

before_script:
  - docker-compose up -d --force-recreate
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - cp .env.ci .env
  - go test -v -cover -coverpkg=./... ./pkg/... -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - rm .env
  - go test -v -cover -coverpkg=./... ./godog_test.go
  - CGO_ENABLED=0 go build -o ./bin/app ./cmd/app.go
  - CGO_ENABLED=0 go build -o ./bin/migrate ./cmd/migrate.go

after_script:
  - docker-compose stop
