version: '3.8'

services:
    mariadb:
        image: "mariadb:10.5.2"
        container_name: "mariadb"
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: "changeme"
        ports:
            - "3306:3306"
        networks:
            - "default"
