version: '3'

services:
    migrate:
        build: "docker/local"
        container_name: "migrate"
        restart: "no"
        working_dir: /var/www
        command: "go run ./cmd/migrate/migrate.go"
        environment:
            DATABASE_DSN: "root:changeme@tcp(mariadb:3306)"
        networks:
            - "default"
        volumes:
            - "./:/var/www"
        depends_on:
            - mariadb
        #Todo: run as non-root user
        user: '0:0'

    app:
        build: "docker/local"
        container_name: "app"
        restart: "no"
        working_dir: /var/www
        command: "dlv debug --headless --listen=:4000 --only-same-user=false --api-version=2 --accept-multiclient --log --log-output=rpc ./cmd/app/main.go"
        environment:
            DATABASE_DSN: "root:changeme@tcp(mariadb:3306)"
        ports:
            - "8989:8002"
            - "4000:4000"
        networks:
            - "default"
        volumes:
            - "./:/var/www"
        depends_on:
            - migrate
        #Todo: run as non-root user
        user: '0:0'

    mariadb:
        image: "mariadb:10.5.9"
        container_name: "mariadb"
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: "changeme"
        ports:
            - "3366:3306"
        networks:
            - "default"
        volumes:
            - "./.var/mysql:/.var/lib/mysql"

    mariadb_test:
        image: "mariadb:10.5.9"
        container_name: "mariadb_test"
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: "changeme"
        ports:
            - "3367:3306"
        networks:
            - "default"

#    postgres:
#        image: "postgres:10.4"
#        container_name: "postgres"
#        restart: "no"
#        environment:
#            POSTGRES_USER: "root"
#            POSTGRES_PASSWORD: "changeme"
#            POSTGRES_DB: "medzoner"
#        ports:
#            - "5432:5432"
#        networks:
#            - "default"
#        volumes:
#            - "./.var/lib/postgresql:/.var/lib/postgresql"