version: '3'

services:
    mariadb:
        image: "mariadb"
        container_name: "mariadb"
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: "changeme"
        ports:
            - "3366:3306"
        networks:
            - "default"
        volumes:
            - "./var/mysql:/var/lib/mysql"

    mariadb_test:
        image: "mariadb"
        container_name: "mariadb_test"
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: "changeme"
        ports:
            - "3367:3306"
        networks:
            - "default"

#    postgres:
#        image: "postgres:10.4"
#        container_name: "postgres"
#        restart: "no"
#        environment:
#            POSTGRES_USER: "root"
#            POSTGRES_PASSWORD: "changeme"
#            POSTGRES_DB: "medzoner"
#        ports:
#            - "5432:5432"
#        networks:
#            - "default"
#        volumes:
#            - "./var/lib/postgresql:/var/lib/postgresql"