services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "4417:4317"
      - "4418:4318"
    environment:
      - LOG_LEVEL=debug


#  docker run \
#  -v "${PWD}/otel-local-config.yaml":/otel-local-config.yaml \
#  -p 4318:4318 -p 4317:4317 \
#  otel/opentelemetry-collector \
#  --config otel-local-config.yaml;

  otel:
    image: otel/opentelemetry-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
        - "${PWD}/otel-local-config.yaml:/otel-local-config.yaml"
    command: --config otel-local-config.yaml
