version: '3'

services:
    app:
        image: "golang:1.17.6"
        container_name: "app"
        restart: "no"
        working_dir: /var/www
        command: "./run_debug.sh"
        #command: make start
        environment:
            DATABASE_DSN: "root:changeme@tcp(mariadb:3306)"
        ports:
            - "8989:8002"
            - "4000:4000"
        networks:
            - "default"
        volumes:
            - "./:/var/www"
        depends_on:
            - mariadb
        cap_add:
            - SYS_PTRACE
        security_opt:
            - "apparmor=unconfined"

    mariadb:
        image: "mariadb:10.5.9"
        container_name: "mariadb"
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: "changeme"
        ports:
            - "3366:3306"
        networks:
            - "default"
        volumes:
            - "./var/mysql:/var/lib/mysql"

    mariadb_test:
        image: "mariadb:10.5.9"
        container_name: "mariadb_test"
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: "changeme"
        ports:
            - "3367:3306"
        networks:
            - "default"

#    postgres:
#        image: "postgres:10.4"
#        container_name: "postgres"
#        restart: "no"
#        environment:
#            POSTGRES_USER: "root"
#            POSTGRES_PASSWORD: "changeme"
#            POSTGRES_DB: "medzoner"
#        ports:
#            - "5432:5432"
#        networks:
#            - "default"
#        volumes:
#            - "./var/lib/postgresql:/var/lib/postgresql"