version: '3'

services:
    mariadb:
        image: "mariadb"
        container_name: "mariadb"
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: "changeme"
        ports:
            - "3306:3306"
        networks:
            - "default"
        volumes:
            - "./var/mysql:/var/lib/mysql"
