# nonk8s
apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: k8s-skaffold
#build:
#  artifacts:
#  - image: localhost:5000/medzoner-go
#    context: docker/local
#  local:
#    useDockerCLI: false
#    useBuildkit: false

manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: medzoner-go
    namespace: default
    port: 4000
    localPort: 4000
  - resourceType: service
    resourceName: medzoner-go
    namespace: default
    port: 8002
    localPort: 8025

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: localhost:5000/medzoner-go
          context: ''
#          hooks:
#            after:
#              - command:
#                  - sh
#                  - -cx
#                  - |
#                    docker tag localhost:5000/medzoner-go localhost:5000/medzoner-go:latest
#                    docker push localhost:5000/medzoner-go:latest
          docker:
            buildArgs:
              ENV: development
            target: run
            cacheFrom:
              - localhost:5000/medzoner-go:latest
#          sync:
#            manual:
#              - src: 'pkg/**/*.go'
#                dest: /var/www/.
