// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/Medzoner/gomedz/pkg/captcha"
	"github.com/Medzoner/gomedz/pkg/http"
	"github.com/Medzoner/gomedz/pkg/http/adapter/gin"
	"github.com/Medzoner/gomedz/pkg/http/probes"
	"github.com/Medzoner/gomedz/pkg/http/server"
	"github.com/Medzoner/gomedz/pkg/logger"
	"github.com/Medzoner/gomedz/pkg/observability"
	"github.com/Medzoner/gomedz/pkg/validation"
	"github.com/Medzoner/medzoner-go/internal/application/command"
	"github.com/Medzoner/medzoner-go/internal/application/event"
	"github.com/Medzoner/medzoner-go/internal/application/query"
	"github.com/Medzoner/medzoner-go/internal/application/service/mailer"
	"github.com/Medzoner/medzoner-go/internal/config"
	"github.com/Medzoner/medzoner-go/internal/domain/repository"
	"github.com/Medzoner/medzoner-go/internal/ui/http/handler"
	"github.com/Medzoner/medzoner-go/internal/ui/http/templater"
	"github.com/Medzoner/medzoner-go/pkg/database"
	"github.com/Medzoner/medzoner-go/pkg/notification"
	"github.com/Medzoner/medzoner-go/test"
	mocks2 "github.com/Medzoner/medzoner-go/test/mocks"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitDbMigration() (database.DbMigration, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return database.DbMigration{}, err
	}
	databaseConfig := configConfig.Database
	dbSQLInstance := database.NewDbSQLInstance(databaseConfig)
	dbMigration := database.NewDbMigration(dbSQLInstance, databaseConfig)
	return dbMigration, nil
}

func InitServerTest(ctx context.Context, m *mocks.Mocks) (server.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return server.Server{}, err
	}
	loggerConfig := configConfig.Logger
	loggerInterface, err := logger.NewLogger(loggerConfig)
	if err != nil {
		return server.Server{}, err
	}
	observabilityConfig := configConfig.Obs
	telemetry, err := observability.NewTelemetry(ctx, observabilityConfig, loggerInterface)
	if err != nil {
		return server.Server{}, err
	}
	serverConfig := configConfig.Server
	ginadapterConfig := configConfig.Engine
	authConfig := configConfig.Auth
	engine := ginadapter.New(ginadapterConfig, authConfig)
	v := closers(telemetry)
	probesPingers := pingers()
	probesHandler := probes.New(serverConfig, probesPingers)
	templateHTML := templater.NewTemplateHTML(configConfig)
	mockTechnoRepository := m.TechnoRepository
	listTechnoQueryHandler := query.NewListTechnoQueryHandler(mockTechnoRepository)
	mockContactRepository := m.ContactRepository
	mockMailer := m.Mailer
	contactCreatedEventHandler := event.NewContactCreatedEventHandler(mockMailer)
	createContactCommandHandler := command.NewCreateContactCommandHandler(mockContactRepository, contactCreatedEventHandler)
	validatorAdapter := validation.New()
	captchaConfig := configConfig.Recaptcha
	recaptchaAdapter := captcha.NewRecaptchaAdapter(captchaConfig)
	indexHandler := handler.NewIndexHandler(templateHTML, listTechnoQueryHandler, createContactCommandHandler, validatorAdapter, recaptchaAdapter)
	v2 := controllers(probesHandler, indexHandler)
	serverServer := server.NewServer(loggerInterface, telemetry, serverConfig, engine, v, v2...)
	return serverServer, nil
}

func InitServer(ctx context.Context) (server.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return server.Server{}, err
	}
	loggerConfig := configConfig.Logger
	loggerInterface, err := logger.NewLogger(loggerConfig)
	if err != nil {
		return server.Server{}, err
	}
	observabilityConfig := configConfig.Obs
	telemetry, err := observability.NewTelemetry(ctx, observabilityConfig, loggerInterface)
	if err != nil {
		return server.Server{}, err
	}
	serverConfig := configConfig.Server
	ginadapterConfig := configConfig.Engine
	authConfig := configConfig.Auth
	engine := ginadapter.New(ginadapterConfig, authConfig)
	v := closers(telemetry)
	probesPingers := pingers()
	probesHandler := probes.New(serverConfig, probesPingers)
	templateHTML := templater.NewTemplateHTML(configConfig)
	technoJSONRepository := repository.NewTechnoJSONRepository(configConfig)
	listTechnoQueryHandler := query.NewListTechnoQueryHandler(technoJSONRepository)
	databaseConfig := configConfig.Database
	dbSQLInstance := database.NewDbSQLInstance(databaseConfig)
	mysqlContactRepository := repository.NewMysqlContactRepository(dbSQLInstance)
	notificationConfig := configConfig.Mailer
	mailerSMTP := notification.NewMailerSMTP(notificationConfig)
	contactCreatedEventHandler := event.NewContactCreatedEventHandler(mailerSMTP)
	createContactCommandHandler := command.NewCreateContactCommandHandler(mysqlContactRepository, contactCreatedEventHandler)
	validatorAdapter := validation.New()
	captchaConfig := configConfig.Recaptcha
	recaptchaAdapter := captcha.NewRecaptchaAdapter(captchaConfig)
	indexHandler := handler.NewIndexHandler(templateHTML, listTechnoQueryHandler, createContactCommandHandler, validatorAdapter, recaptchaAdapter)
	v2 := controllers(probesHandler, indexHandler)
	serverServer := server.NewServer(loggerInterface, telemetry, serverConfig, engine, v, v2...)
	return serverServer, nil
}

// wire.go:

func controllers(p *probes.Handler, a handler.IndexHandler) []http.Controller {
	return []http.Controller{
		p,
		a,
	}
}

func closers(tl observability.Telemetry) []server.Closer {
	return []server.Closer{
		tl,
	}
}

func pingers() probes.Pingers {
	return []probes.Probes{}
}

var (
	CommonWiring = wire.NewSet(config.NewConfig, wire.FieldsOf(
		new(config.Config),
		"Obs",
		"Engine",
		"Logger",
		"Auth",
		"Server",
		"Mailer",
		"Database",
		"Recaptcha",
	), pingers, probes.New,
	)
	ServerWiring = wire.NewSet(ginadapter.New, wire.Bind(new(server.Enginer), new(*ginadapter.Engine)), controllers,
		closers, server.NewServer,
	)
	ObsWiring     = wire.NewSet(logger.NewLogger, observability.NewTelemetry)
	UsecaseWiring = wire.NewSet(event.NewContactCreatedEventHandler, command.NewCreateContactCommandHandler, query.NewListTechnoQueryHandler, wire.Bind(new(event.IEventHandler), new(*event.ContactCreatedEventHandler)))
	HandlerWiring = wire.NewSet(handler.NewIndexHandler, handler.NewNotFoundHandler)

	InfraWiring      = wire.NewSet(templater.NewTemplateHTML, validation.New, captcha.NewRecaptchaAdapter, wire.Bind(new(templater.Templater), new(*templater.TemplateHTML)), wire.Bind(new(validation.Validater), new(*validation.ValidatorAdapter)), wire.Bind(new(captcha.Captcher), new(*captcha.RecaptchaAdapter)))
	DbWiring         = wire.NewSet(database.NewDbSQLInstance, wire.Bind(new(database.DbInstantiator), new(*database.DbSQLInstance)))
	MailerWiring     = wire.NewSet(notification.NewMailerSMTP, wire.Bind(new(mailer.Mailer), new(*notification.MailerSMTP)))
	MailerMockWiring = wire.NewSet(wire.FieldsOf(
		new(*mocks.Mocks),
		"Mailer",
	), wire.Bind(new(mailer.Mailer), new(*mocks2.MockMailer)),
	)
	RepositoryWiring     = wire.NewSet(repository.NewTechnoJSONRepository, repository.NewMysqlContactRepository, wire.Bind(new(repository.TechnoRepository), new(*repository.TechnoJSONRepository)), wire.Bind(new(repository.ContactRepository), new(*repository.MysqlContactRepository)))
	RepositoryMockWiring = wire.NewSet(wire.FieldsOf(
		new(*mocks.Mocks),
		"TechnoRepository",
	), wire.Bind(new(repository.TechnoRepository), new(*mocks2.MockTechnoRepository)), wire.FieldsOf(
		new(*mocks.Mocks),
		"ContactRepository",
	), wire.Bind(new(repository.ContactRepository), new(*mocks2.MockContactRepository)),
	)
	AppWiring = wire.NewSet(event.NewContactCreatedEventHandler, command.NewCreateContactCommandHandler, query.NewListTechnoQueryHandler, wire.Bind(new(event.IEventHandler), new(*event.ContactCreatedEventHandler)))
	UiWiring  = wire.NewSet(handler.NewIndexHandler, handler.NewNotFoundHandler)
)
