// Code generated by MockGen. DO NOT EDIT.
// Source: ./techno_repository.go
//
// Generated by this command:
//
//	mockgen -destination=../../../test/mocks/techno_repository.go -package=mocks -source=./techno_repository.go TechnoRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTechnoRepository is a mock of TechnoRepository interface.
type MockTechnoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTechnoRepositoryMockRecorder
	isgomock struct{}
}

// MockTechnoRepositoryMockRecorder is the mock recorder for MockTechnoRepository.
type MockTechnoRepositoryMockRecorder struct {
	mock *MockTechnoRepository
}

// NewMockTechnoRepository creates a new mock instance.
func NewMockTechnoRepository(ctrl *gomock.Controller) *MockTechnoRepository {
	mock := &MockTechnoRepository{ctrl: ctrl}
	mock.recorder = &MockTechnoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTechnoRepository) EXPECT() *MockTechnoRepositoryMockRecorder {
	return m.recorder
}

// FetchStack mocks base method.
func (m *MockTechnoRepository) FetchStack(ctx context.Context) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchStack", ctx)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchStack indicates an expected call of FetchStack.
func (mr *MockTechnoRepositoryMockRecorder) FetchStack(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchStack", reflect.TypeOf((*MockTechnoRepository)(nil).FetchStack), ctx)
}
